### ISSUE TITLE
Support Cursor Keys in normal mode

### ISSUE THREAD

**Issue by MarkuBu** [vamolessa/pepper#10]
I know it's a no go, but I don't have a regular keyboard with qwerty and dedicated cursor keys. I have a Redox keyboard (split matrix keyboard like Ergodox).

My layout is not standard qwerty. hjkl are scattered around the keyboard.  Instead I use cursor keys on a second layer.

It would things easier for me if I can use cursor keys in normal mode instead hjkl

**Comment by vamolessa** [comment]
You can add a mapping (https://github.com/vamolessa/pepper/blob/master/rc/config_recipes.md#keybindings) for your keyboard and use whatever key you want:

```
map -normal <left> h
map -normal <down> j
map -normal <up> k
map -normal <right> l
```

**Comment by vamolessa** [comment]
Forgot to mention that you add this to your config file which you normally source at startup using the cli flag `--config` (or `-c` for short) as stated here: https://github.com/vamolessa/pepper/blob/master/rc/config_recipes.md#load-config-file-on-startup.

Also, if you need further help, please feel free to re-open this issue.
