### ISSUE TITLE
language syntax definition ends in 404

### ISSUE THREAD

**Issue by MarkuBu** [vamolessa/pepper#11]
The language syntax definition link on help.md ends in a 404 page

https://github.com/vamolessa/pepper/blob/master/rc/help.md

**Comment by vamolessa** [comment]
Thanks for catching it. I forgot the `.md` extension. Should be working now!

**Comment by MarkuBu** [comment]
Sorry to bother you, but the README link also fails

**Comment by vamolessa** [comment]
Wait, which README?
The one in the root works both in github and github pages.

**Comment by MarkuBu** [comment]
also on the help.md page
