### ISSUE TITLE
How do I use lsp?

### ISSUE THREAD

**Issue by MarkuBu** [vamolessa/pepper#12]
I set up pepper and rust analyzer. If I open a *.rs file pepper tells me that the rust analyzer is started. But how can I use it?

**Comment by MarkuBu** [comment]
I got it

**Comment by naveedpash** [comment]
Can you elaborate?

I started pepper with the same config file as the example

I don't get any message that rust-analyzer has been started

When I try to use `gd` and other lsp related keybindings, I get a message saying `lsp server not started`

**Comment by MarkuBu** [comment]
In my case the analyzer was running. I just didn't know how to use it. But currently I don't use Pepper anymore. I use neovim for now

**Comment by vamolessa** [comment]
Did you setup your lsp server config like: https://github.com/vamolessa/pepper/blob/master/rc/config_recipes.md#run-lsp-server-automatically ?
I never tested with `gd`. Which source files does it work on?
When you try that config, could you confirm that you can open the lsp log once you open a source file?
