### ISSUE TITLE
pepper panics when opening a file

### ISSUE THREAD

**Issue by malte-v** [vamolessa/pepper#18]
Most of the time, I can't open any file with pepper (latest git rev as of writing, `pepper` binary from the `mine` crate). The following is written to `pepper-crash.txt`: 
```
panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', pepper/src/application.rs:351:55
```
Judging from the source code, the problem seems to have something to do with updating the display upon opening a file. No idea how to fix it though :/

**Comment by vamolessa** [comment]
Would you mind cheking the latest commit on `master`?
I noticed I was opening `dev/tty` with `NONBLOCK`.

**Comment by malte-v** [comment]
That fixed it. Thank you!
