### ISSUE TITLE
Cursor is sometimes hidden by minibuffer

### ISSUE THREAD

**Issue by malte-v** [vamolessa/pepper#19]
When editing some code at the bottom of the screen, the cursor is sometimes hidden by documentation or auto-suggestions popping up in the minibuffer, making it impossible to see the currently edited text. I'd suggest to automatically scroll down by the needed amount in that case.

**Comment by vamolessa** [comment]
It's now fixed in `v0.18.4`.
Also, I've added the config `status_bar_max_height` that controls how height a statusbar message can get.

**Comment by malte-v** [comment]
Thanks!
