### ISSUE TITLE
Advantages of "selection mode" over Kakoune-like "select by default"?

### ISSUE THREAD

**Issue by malte-v** [vamolessa/pepper#21]
I'm considering moving from Kakoune over to pepper, but one thing that bugs me is the separate "selection mode" with the blue cursor. I feel like it consistently requires more or the same number of keystrokes compared to vi or Kakoune.

Here's an example: I'm at the beginning of the line
```
map-command <c-e> <c-p>
```
in normal mode and I want to change `command` to `insert`. Here's how I would do it with vi/kakoune/pepper:
- vi: `eece`
- kakoune: `eeec`
- pepper: `wwawi`

Is five keystrokes the best pepper can do in this situation or have I missed the point of the separate "selection mode"?

**Comment by vamolessa** [comment]
Well, I really did not design the default bindings/editing primitives trying to beat vim or kakoune.
Instead my goal was to settle on a very minimal and orthogonal set of primitives that compose.
You can see that the list here is pretty small: https://github.com/vamolessa/pepper/blob/master/pepper/rc/bindings.md

So I decided to take the hit of typing a little bit more in some cases.
Note that kakoune has a lot of `<alt-something>` bindings for the 'something' vs 'something-but-expanding-the-selection' which was one thing I didn't like when using that editor.

Hope you can understand the reasoning.

**Comment by malte-v** [comment]
If minimalism is your explicit goal, I think you reached it :) I'd rather have a larger set of editing primitives that fully make use of the keyboard and enable me to edit text more efficiently, but clearly we have different goals here.
