### ISSUE TITLE
change cursor shape to a bar, how?

### ISSUE THREAD

**Issue by moesasji** [vamolessa/pepper#23]
With a caret style cursor editing I find it more intuitive if the default cursor looks like a vertical bar instead of a box. That way if a cursor looks like a box I know that I have selected something. At the same time this avoids having to keep in mind that things change at the left of the box/cursor as changes only happen where the bar/line and or the selected box is.

Is there a way to change the cursor shape in pepper to a line/bar to get this behavior?

**Comment by vamolessa** [comment]
That would certainly be a nice improvement. However, as far as I'm aware, there's no way to draw a vertical bar between two grid positions in a terminal. Given that Pepper has multi-cursors, we can't just use the terminal's cursor and be done with it unfortunately.

I'll leave this open for a while in case anyone can come up with a solution/suggestion for this!

**Comment by vamolessa** [comment]
Since I don't think this is possible for text UIs, will close.
