### ISSUE TITLE
LSP find references causes crash on macOS

### ISSUE THREAD

**Issue by kevinsjoberg** [vamolessa/pepper#28]
I'm working on the pepper codebase using `rust-analyser`. Pressing `gr` to find references causes pepper to crash on macOS. See the log below.

<details>
<summary>pepper-crash.txt</summary>

```console
panicked at 'forgot to call 'finish' on ServerEventIter', plugin-lsp/src/protocol.rs:973:9
```
</details>

OS: macOS 12.0.1
Terminal: Kitty 0.24.2
pepper: 0.22.0

**Comment by vamolessa** [comment]
found the issue causing the crash and fixed on master. however, it's not currently showing the reference context still probably because of what's causing #27
