### ISSUE TITLE
Integrating with external processes

### ISSUE THREAD

**Issue by kevinsjoberg** [vamolessa/pepper#29]
👋 @vamolessa, this is not so much an issue than it is a question.

I read that one of pepper's goals were `Extensible through external cli tools` on the [Handmade Network's website](https://pepper-editor.handmade.network). Is this true, and if so, how?

I'm coming from [dte](https://craigbarnes.gitlab.io/dte/) and was hoping pepper would provide some of the same features as `dte` provides when it comes to integrating with external tools. `dte` has a section on [External Commands](https://craigbarnes.gitlab.io/dte/dterc.html#external-commands) and I've found the following really useful:

| command | description | pepper equivalent |
| ---------- | ----------- | ------------------ |
| [filter](https://craigbarnes.gitlab.io/dte/dterc.html#filter) | Filter selected text or whole file through external command. | ? |
| [run](https://craigbarnes.gitlab.io/dte/dterc.html#run) | Run external command. | ? |
| [exec-open](https://craigbarnes.gitlab.io/dte/dterc.html#exec-open) | Run external command and open all filenames listed on its standard output. | find-file (sort of) |

The main thing in `dte` I find powerful is the concept of `exec`. In [Unify commands that run external programs into a single "exec" command](https://gitlab.com/craigbarnes/dte/-/issues/110) this concept is explored further where a single construct, `exec`, can be used to implement a handful of other useful commands.

I really love being able to run `:run tig blame $FILE` to temporarily open `tig`'s blame view on the current file and after exiting ending back in my editor. `exec-open` allows me to run an external program such as `fzf` and then see the selected files opened in `dte`.

**Comment by kevinsjoberg** [comment]
Appreciate the detailed reply, @vamolessa. I've been dealing with some personal matters, so sorry for the late reply.

> `$` will also prompt a readline for a command, but will only execute it with no piping. This is most useful for one shot things like "open a new terminal split with git on the same dir";

I have yet to see this work. Could you provide some examples of this? Whenever I press `$` and type in a command (e.g., `tig`) nothing happens.

> How do usually use that `filter` when selecting selections?

In [dte](https://craigbarnes.gitlab.io/dte/), [filter](https://craigbarnes.gitlab.io/dte/dterc.html#filter) works on the current file (or the current line if `-l` is provided) when no selection is found. I tend to use it for things like formatting the file (e.g., `:filter elm-format --stdin`). I think it works similar to what `|` does in pepper, right?

> Would | or ! or $ suffice to replicate that run command?

Maybe. I still need to understand `$` better. I use [run](https://craigbarnes.gitlab.io/dte/dterc.html#run) for all kinds of things. Opening [tig](https://jonas.github.io/tig/) in the root directory using `:run tig`, git blaming the current file using `:run tig blame $FILE` where `$FILE` is the path to the file in the active buffer. I use it to run a [file manager](https://github.com/jarun/nnn) using `:run nnn` and a lot of other different use cases.

> That exec-open is also interesting, but do you use it in the middle of a coding session or right after you open the editor?

[exec-open](https://craigbarnes.gitlab.io/dte/dterc.html#exec-open) is just another command. I use it all the time to open files in the middle of a coding session. I have the following binding in dte:

    bind C-P 'exec-open fzf --multi --preview="cat {}"'

This will spawn [fzf](https://github.com/junegunn/fzf) and allow me to select files (with a preview). Whenever I press enter the selected files open in `dte`. It's really nice. Basically whatever the command to `exec-open` outputs to stdout, will be treated as file paths that dte will open (one file per line).

Hope this makes things more clear. 🙂

**Comment by kevinsjoberg** [comment]
> Were you expecting tig to take over pepper's terminal window? Because that's kinda hard since it's the server (a background process) that spawns the processes so it can't 'see' its clients ttys. What I usually do is to communicate with the terminal telling it to spawn a new split with the program I want to run there. It's also what Kakoune does if I'm not mistaken.

Right, that makes sense. Thank you for the clarification. 🙂 

> Also, there is no variable of sort that expand into bufferpath or something. Pepper commands are really simple, it just interprets a line and that's it. However, it's possible to implement more complex behaviors by integrating a plugin. However that would mean coding in rust and using the pepper crate and then building your own code editor.

Would it make sense to expansions? Initially, perhaps the path to the current buffer. In Vim, there's [filename modifiers](https://vimhelp.org/cmdline.txt.html#filename-modifiers) and in Kakoune there's [expansions](https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc). For instance, if you want to interactively blame the current file using `tig blame` or run any CLI command for the current file really. It's not always possible to just work with stdin and writing specific plugins for one-off use cases feel a bit over the top.

> However it should also be possible to actually use fzf by using the 'communicate with the terminal' trick. You can invoke pepper like pepper --as-focused-client --quit <files to open...> which will connect to the server acting like the currently focused client, send it commands to open all the files listed and then quit right after.
By using something like xargs you are able to redirect the fzf selections as file to open in the current client.

Right. I keep forgetting that we have a server/client architecture. This is really helpful, thanks! 👍 

> Hope this helps you better configure it for your needs.
Some solutions may seem kinda convoluted right now, but it's what you CAN do right now.
In the future plugins may be easier to write and consequently make it easier to hack pepper.

Absolutely. I appreciate you're taking the time to help me. I really like the overall approach pepper takes! ❤️

**Comment by vamolessa** [comment]
> Right, that makes sense. Thank you for the clarification. 🙂

No problem!

> Would it make sense to support some kind of expansion out of the box? Initially, perhaps the path to the current file. In Vim, there's [filename modifiers](https://vimhelp.org/cmdline.txt.html#filename-modifiers) and in Kakoune there's [expansions](https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc). For instance, if you want to interactively blame the current file using tig blame, run the tests for the current file, or run any CLI command on the current file really. It's not always possible to just work with stdin and writing specific plugins for one-off use cases feel a bit over the top.

That would make sense, yes! It's in fact something I tried doing before a couple of times but was never satisfied with the design. Which is why I ended up removing it entirely. However, that document about Kakoune's expansions is something that I did now find at the time and already inspired me some solution for pepper :)

> Right. I keep forgetting that we have a server/client architecture. This is really helpful, thanks!

Alright! Cool!

> Absolutely. I appreciate you're taking the time to help me. I really like the overall approach pepper takes! ❤️

Thank you so much! I'm glad it's of use for other people and thanks for the reports so far :)
