### ISSUE TITLE
Yank/Paste does not work on macOS

### ISSUE THREAD

**Issue by kevinsjoberg** [vamolessa/pepper#33]
I just noticed that I can't yank (`y`) or paste (`Y`) on macOS even though my `copy-command` is set to `pbcopy` and `paste-command` is set to `pbpaste`. Nothing happens when pressing `y` and `Y` just clears the selection without every pasting anything from the clipboard.

**Comment by vamolessa** [comment]
Does it work if manually invoking from a `|` action?
Like: open a buffer, and then `|pbpaste<enter>` while having some text in your system clipboard?
Does it paste it to the buffer?

Does selecting some text in the buffer and then `|pbcopy<enter>` correctly puts the buffer's selection in your system clipboard?

**Comment by kevinsjoberg** [comment]
Sorry for the delay, @vamolessa. It doesn't look like `pbcopy` and `pbpaste` work there either. I tried to do `!pbaste` without success (nothing got pasted). I also tried to select a line and then do `$pbcopy` without success (the line was not copied to my clipboard).

**Comment by vamolessa** [comment]
Would you also check the newest version (`0.24.0`)?

**Comment by kevinsjoberg** [comment]
Still nothing, unfortunately.

**Comment by vamolessa** [comment]
Oh I was reading the pbpaste manual and it seems that it can produce output with different encoding. Maybe try forcing to uftf8 my setting this env var before running pepper: `LANG=en_US.UTF-8`

**Comment by kevinsjoberg** [comment]
It's already set to the correct value, `en_US.UTF-8`. So probably not encoding related. It seems like pepper is the only program I've tested with where it doesn't work.

**Comment by vamolessa** [comment]
It seems to be fixed now. The culprit was `libc::daemon` which is deprecated on mac. On `0.26.0` it's no longer used on unix platforms.

Please reopen if you still find it not working!
