### ISSUE TITLE
cargo install pepper-plugin-lsp installs older pepper version

### ISSUE THREAD

**Issue by MarkuBu** [vamolessa/pepper#34]
Hi, I want to try pepper. I installed pepper without lsp first and I got version 0.23.3. Then I want to use the lsp version, but this uses the v0.22.0

Is it possible to get the current pepper version with lsp support?

**Comment by kevinsjoberg** [comment]
By default, `cargo install` will use https://crates.io to install the given crate. Which happens to be [pepper-plugin-lsp](https://crates.io/crates/pepper-plugin-lsp). You can build a local version by providing `--path`.

```console
pepper $ cargo install --path mine
```

**Comment by vamolessa** [comment]
Oh, it seems that when releasing 0.23, I forgot to update the lsp plugin dependency.
Please build [from source](https://github.com/vamolessa/pepper#from-source) in the mean time, or wait a little bit for the 0.24 release.

**Comment by vamolessa** [comment]
This should now be fixed as `0.24.0` is live
