### ISSUE TITLE
I created the keymaps cheat sheet

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#35]
Just want to contribute a bit for the project, feel free to add this to the `README.md` file or [the bindings wiki](https://github.com/vamolessa/pepper/wiki/bindings).

![pepper](https://user-images.githubusercontent.com/43980777/156891729-b17632a6-c86f-40cf-9db8-58bc90b73ec2.png)

- PNG image file: https://user-images.githubusercontent.com/43980777/156891729-b17632a6-c86f-40cf-9db8-58bc90b73ec2.png
- KLE link: http://www.keyboard-layout-editor.com/#/gists/175ca15e15b350e1a2a808fe0b5eecb5

If you want to change/improve anything on this cheat sheet, you could go to the KLE link then edit it later on!

**Comment by vamolessa** [comment]
Oh this is great! Will add to README
