### ISSUE TITLE
Feature: text-object for paragraphs

### ISSUE THREAD

**Issue by leahneukirchen** [vamolessa/pepper#4]
I tried defining one using c-j/c-k but it's difficult in general when you are at the beginning or end of buffer.

**Comment by vamolessa** [comment]
would `map -normal ap gh<c-k>cv<c-j>gl` work?
![paragraph-selection-object](https://user-images.githubusercontent.com/1696072/119202415-4029e600-ba80-11eb-9bee-ff610cb7358c.gif)

**Comment by leahneukirchen** [comment]
Looks good, I'll try this.

**Comment by vamolessa** [comment]
Will close for now as that may be enough solution. If further help is need, please just re-open the issue!
