### ISSUE TITLE
Better default `copy-command` and `paste-command`

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#48]
Pepper currently can pick commands for clipboard handling pretty fine but could be improve by supporting [`xclip`](https://github.com/astrand/xclip) and Wayland's [`wl-clipboard`](https://github.com/bugaevc/wl-clipboard):
- If on Wayland then use `wl-clipboard`:
  - Copy: `wl-copy`
  - Paste: `wl-paste --no-newline`
- Else if on X11:
  - If `xclip` is installed then use it:
    - Copy: `xclip -in -selection clipboard`
    - Paste: `xclip -out -selection clipboard`
  - Else use `xsel` as currently is.

You could check out [`clipb`](https://github.com/NNBnh/clipb) a clipboard managers warper that I write [(relevant code)](https://github.com/NNBnh/clipb/blob/main/bin/clipb#L42-L65).

**Comment by vamolessa** [comment]
Does `xclip -selection clipboard -in` work on wayland? That is the default config on linux (https://github.com/vamolessa/pepper/blob/master/pepper/rc/default_configs.pepper#L59).

I think it probably makes more sense to keep it the way it is and let users who prefer to change the default clipboard manager by using the [`copy-command`](https://github.com/vamolessa/pepper/blob/master/pepper/rc/command_reference.md#copy-command) and [`paste-command`](https://github.com/vamolessa/pepper/blob/master/pepper/rc/command_reference.md#paste-command) commands in their config file.

**Comment by NNBnh** [comment]
> Does `xclip -selection clipboard -in` work on wayland?

Unfortunately `xsel` and `xclip` doesn't work on Wayland.

> I think it probably makes more sense to keep it the way it is and let users who prefer to change the default clipboard manager by using the [`copy-command`](https://github.com/vamolessa/pepper/blob/master/pepper/rc/command_reference.md#copy-command) and [`paste-command`](https://github.com/vamolessa/pepper/blob/master/pepper/rc/command_reference.md#paste-command) commands in their config file.

Yeah okay.
