### ISSUE TITLE
Support mark all cursor's position and selection

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#54]
We currently have:

| keys | action |
| --- | --- |
| `m<char>` | save current buffer and main cursor position as a marker on register `<char>` |
| `M<char>` | go to marker on register `<char>` (if it's a valid marker) |

But I wish it can behave like Kakoune:
- User could mark all cursor's position and selection (if in selection mode) as a marker on a register.
- Then user can not only just go to that marker but restore all of that cursor's position and selection.

This will help user utilize the power of multi cursor way better.

**Comment by vamolessa** [comment]
This should be possible by comming up with a syntax for filepath + multiple cursors.
It could have the potential of even allowing opening a file with cursors at multiple locations.
Maybe something like `pepper path/to/file.txt:2,5;6,1`

**Comment by vamolessa** [comment]
This will be possible in v0.29.0 (currently on `parse-multi-cursors` branch).

**Comment by vamolessa** [comment]
it's now on `0.29.0`
