### ISSUE TITLE
Add clear main selection key

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#57]
We currently have:

| keys | action |
| --- | --- |
| `cd` | clear all extra cursors and keep only the main cursor |

But there is no way to clear only the main cursor...

From [Kakoune's keys docs](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#multiple-selections):

> <kbd>Alt</kbd>-<kbd>Space</kbd> : Clear the main selection.

I imagine it will be implemented like this:

```diff
  | keys       | action                                                |
  | ---------- | ----------------------------------------------------- |
  | `cd`       | clear all extra cursors and keep only the main cursor |
+ | `cD`, `CD` | clear only the main cursor                            |
```

**Comment by vamolessa** [comment]
I've moved the current `cd` binding to `CD` (or `cD`) and added a new `cd` which only deletes the main cursor.
It's on c8c46d03 and will be released on `v0.27.0`
