### ISSUE TITLE
Add set the search pattern to the main selection key

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#58]
From [Kakoune's keys docs](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#searching):

> <kbd>\*</kbd> : set the search pattern to the main selection (automatically detects word boundaries).
> <kbd>Alt</kbd>-<kbd>\*</kbd> : set the search pattern to the main selection (verbatim, no smart detection).

I imagine it will be implemented with only one key <kbd>\*</kbd> to set the search pattern to the main selection that:
- ~~In normal mode it will automatically detects word boundaries.~~
- In selection mode it will set it verbatimly, no smart detection.

**Comment by vamolessa** [comment]
Isn't this what the `N` and `P` keys do?

**Comment by NNBnh** [comment]
> Isn't this what the `N` and `P` keys do?

No, it dose not add cursor to the next/previous search match.
It set the search pattern to the main cursor's selection.

For example: If we press <kbd>\*</kbd> when the main cursor is selecting the word "pkgs", this would be equivalent to <code>s<b>pkgs</b>\<enter\></code> (but still keep the user in selection mode with the same position and selection).

I'm fully aware that expansions exist but confused on how to use it with `map`:

```
map normal * "s@{cursor-selection}<enter>"
```

**Comment by vamolessa** [comment]
I'm not exactly sure what you mean

Is this not what you're looking for?
![ezgif-5-ca18dbc2be](https://user-images.githubusercontent.com/1696072/166396148-3a6fbf8a-1bb2-4778-a6d4-991becc6f9ce.gif)

When pressing `N` (or `P`), it searches the word under the cursor.
Also, if there's already a selection, it searches for that selection.

What Kakoune's `*` does differently?
Thanks for clarifying!

**Comment by NNBnh** [comment]
Wait what?!!?!...

Sorry for bothering, I was not figure it out that <kbd>N</kbd>, <kbd>P</kbd> can not only add cursor to the next/previous search match but also set the search pattern (maybe we should note this in `bindings.md`).

This is fantastic, Pepper keep surprise me by how well designed it is!
