### ISSUE TITLE
Will "WORD" movement keys be add?

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#60]
I just realized that Pepper only have word movement but not WORD movement:

| keys | action |
| --- | --- |
| `w`, `b` | move cursors forward/back by word |
| `e` | move cursors forward to the end of the word |
| `W`, `B`, `E` | _doesn't exist_ |

That mean the current keymaps cheat sheet is currently wrong:

![image](https://user-images.githubusercontent.com/43980777/166180432-50ddc0a3-058e-4b12-9da1-78ed05bd1bd2.png)

But will "WORD" movement keys be add in the future? If not I will open a pull request to fix the cheat sheet.

**Comment by vamolessa** [comment]
I have no plans on adding WORD movements at the moment.
I would happily accept a pull request correcting the cheat sheet, thanks :)
