### ISSUE TITLE
[Linux] plugin-lsp: invalid glob pattern

### ISSUE THREAD

**Issue by Houkime** [vamolessa/pepper#66]
A line in `.pepper`

```
lsp rust-analyzer "**.rs"
```
results in `error:glob error: invalid glob` at startup regardless of the file opened, and no LSP starts for .rs. This is the default line `plugin-lsp` recommends.

```
lsp rust-analyzer "*.rs"
```
Results in LSP starting up if and only if Pepper is called from the directory the file resides in.

Pepper was compiled from sources at a commit 3e55af8e8a8b277a9021714ad2ecc2c65654b8ac

**Comment by Houkime** [comment]
This error is also present in 0.27 tag.

**Comment by vamolessa** [comment]
Would you try using `"**/*.rs"` instead?
It seems the documentation is really suggesting an invalid glob.
I'll make sure it's updated in the next release.

**Comment by vamolessa** [comment]
will close as it was fixed. if you find further issues, pleas reopen!
