### ISSUE TITLE
Weird screen flickering when moving cursor on macOS

### ISSUE THREAD

**Issue by hovsater** [vamolessa/pepper#69]
I just upgraded to the latest version of pepper and I'm not seeing weird flickering when moving my cursor up and down in files. See the attached video.

https://user-images.githubusercontent.com/503025/198533578-318780ae-3ee3-4f77-9878-5be65cd5854f.mov

**Comment by vamolessa** [comment]
Oh my bad. That would be because of a forgotten `eprintln` when I was debugging the unix platform layer.
It should be fixed in the latest commit and will be live in the next release!
Thanks
