### ISSUE TITLE
Pepper doesn't send trailing newlines to the LSP server

### ISSUE THREAD

**Issue by praschke** [vamolessa/pepper#70]
This assumption means pepper fails to open files ending with a different character, and also contaminates lsp-format by neglecting to send final newlines in `textDocument/didChange` events, which in my case causes zls to add a second newline to the end of the file.

**Comment by vamolessa** [comment]
Would you mind explaining the issue a little bit further?
I've just tested opening a file that does not have a trailing `\n` and it could open it no problem.
Feel free to send a test file which reproduces the issue.
Thanks!

**Comment by praschke** [comment]
`BufferContent` is printed with newlines between each `BufferLine`, and not on the outside. this is just as needed to represent files without trailing newlines. however, there is a missing `BufferLine` at the end of files with trailing newlines.

```
pepper::buffer::BufferLine ("    }"),
pepper::buffer::BufferLine ("}"),
pepper::buffer::BufferLine ("")
```

this is what i see in gdb from a file with two trailing newlines. it's what i would expect to see from a buffer with one trailing newline.

```
pepper::buffer::BufferLine ("    }"),
pepper::buffer::BufferLine ("}")
```

this is what i see from a file with one trailing newline, and from a file with no trailing newline. i would expect to see this only from a buffer with no trailing newline.

[this looks like the source of the problem.](https://github.com/vamolessa/pepper/blob/master/pepper/src/buffer.rs#L704-L738) popping newlines off of lines then calling `read_line` forgets whether there is an empty line between the last newline and EOF/whether the last character before EOF is a newline.

**Comment by vamolessa** [comment]
Thanks for the thoroughly detailed explanation!
I've just merged your PR. Hopefully that will fix your issues.
It should be out with the `0.31.0` release.

Will close now. Please feel free to reopen should you find further issues.
