### ISSUE TITLE
`g` can't be remapped

### ISSUE THREAD

**Issue by praschke** [vamolessa/pepper#72]
![image](https://user-images.githubusercontent.com/91733887/218516687-2fae8d40-0ef2-4f2b-b43f-b03738014b89.png)

g doesn't open a mode, and when i put `map normal m g` in the config, this happens. i wanted to automatically move all uses of `g` to a different location. i guess without a mode i wouldn't be able to map keys coming after `g` anyway, but i think maybe this still shouldn't happen.

**Comment by vamolessa** [comment]
alright, I can reproduce it now
gonna take a look

**Comment by vamolessa** [comment]
I think it is fixed. I'll continue testing this new version to make sure it's properly working.
Regardless, the fix will be included in the next release.
That said, I'll appreciate it if you could also test it by installing from the latest git commit.

Will close. If anything comes up, please feel free to reopen.
